heat_template_version: 2013-05-23
parameters:
  image:
    type: string
    default: cirros-0.3.2-x86_64-uec
  flavor:
    type: string
    default: m1.nano
  network:
    type: string
  key:
    type: string
resources:
  server:
    type: OS::Nova::Server
    properties:
      image: {get_param: image}
      flavor: {get_param: flavor}
      key_name: {get_param: key}
      networks:
       - network: {get_param: network}
outputs:
  serverip:
    value: {get_attr: [server, networks, {get_param: network}, 0]}
