heat_template_version: 2013-05-23
description: Wordpress
parameters:
  image:
    type: string
    description: Image used for servers
    default: fedora-wp
  key:
    type: string
    description: SSH key to connect to the servers
    default: elynn
  flavor:
    type: string
    description: flavor used by the web servers
    default: m1.small
  database_flavor:
    type: string
    description: flavor used by the db server
    default: m1.small
  network:
    type: string
    description: subnet on which the load balancer will be located
    default: net01
  external_net:
    type: string
    description: external network
    default: public
  database_name:
    type: string
    description: Name of the wordpress DB
    default: wordpress
  database_user:
    type: string
    description: Name of the wordpress user
    default: wordpress
resources:
  database_password:
    type: OS::Heat::RandomString
  database_root_password:
    type: OS::Heat::RandomString
  db:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: database_flavor}
      image: {get_param: image}
      key_name: {get_param: key}
      networks:
        - port: {get_resource: db_port}
      config_drive: True
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/bash -v
            #yum -y install mariadb mariadb-server
            systemctl enable mariadb.service
            systemctl start mariadb.service
            mysqladmin -u root password $db_rootpassword
            cat << EOF | mysql -u root --password=$db_rootpassword
            CREATE DATABASE $db_name;
            GRANT ALL PRIVILEGES ON $db_name.* TO "$db_user"@"%"
            IDENTIFIED BY "$db_password";
            FLUSH PRIVILEGES;
            EXIT
            EOF
          params:
            $db_rootpassword: {get_attr: [database_root_password, value]}
            $db_name: {get_param: database_name}
            $db_user: {get_param: database_user}
            $db_password: {get_attr: [database_password, value]}
  wp:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: database_flavor}
      image: {get_param: image}
      key_name: {get_param: key}
      networks:
        - port: {get_resource: wp_port}
      config_drive: True
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/bash -v
            #yum -y install httpd wordpress
            systemctl enable httpd.service
            systemctl start httpd.service
            setsebool -P httpd_can_network_connect_db=1

            sed -i "/Deny from All/d" /etc/httpd/conf.d/wordpress.conf
            sed -i "s/Require local/Require all granted/" /etc/httpd/conf.d/wordpress.conf
            sed -i s/database_name_here/$db_name/ /etc/wordpress/wp-config.php
            sed -i s/username_here/$db_user/ /etc/wordpress/wp-config.php
            sed -i s/password_here/$db_password/ /etc/wordpress/wp-config.php
            sed -i s/localhost/$db_host/ /etc/wordpress/wp-config.php

            systemctl restart httpd.service
          params:
            $db_name: {get_param: database_name}
            $db_user: {get_param: database_user}
            $db_password: {get_attr: [database_password, value]}
            $db_host: {get_attr: [db, first_address]}
  wp_port:
    type: OS::Neutron::Port
    properties:
      network: {get_param: network}
  db_port:
    type: OS::Neutron::Port
    properties:
      network: {get_param: network}
  fip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: {get_param: external_net}
  fipa:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: {get_resource: fip}
      port_id: {get_resource: wp_port}
outputs:
  wordpress:
    value:
      str_replace:
        template: http://url/wordpress
        params:
          url: {get_attr: [fip, floating_ip_address]}
