heat_template_version: 2014-10-16
parameters:
  network:
    type: string
    default: f3bc1389-2b0a-45d4-a2d8-68ba26703185
resources:
  neststack:
    type: port.yaml
    properties:
      network: {get_param: network}
outputs:
  avail_pool:
    value: {get_attr: [neststack, avail_pool]}
  avail_port:
    value: {get_attr: [neststack, avail_port]}
