#cloud-config

apt_sources:
  - source: "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
  - source: "deb-src http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
packages:
  - git
  - libxml2-dev
  - libxslt1-dev
  - libpq-dev
  - bridge-utils
  - ebtables
users:
  - default
  - name: stack
    gecos: devstack user
    lock-passwd: False
    plain_text_passwd: {get_param: user_passwd}
    shell: /bin/bash
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    homedir: /opt/stack
ssh_pwauth: True
write_files:
  - path: /tmp/local.conf
    content: {get_file: local.conf}
    permissions: '0666'
  - path: /tmp/install.sh
    content: {get_file: install.sh}
    permissions: '0755'
  - path: /etc/sudoers.d/999-stack-requiretty
    permissions: 440
    content: |
      Defaults:stack !requiretty
