heat_template_version: 2013-05-23
parameters:
 flavor:
    type: string
    default: m1.nano
 image:
    type: string
    default: cirros-0.3.2-x86_64-uec
resources:
   stack:
    type: OS::Heat::Stack
    properties:
      context:
        region_name: RegionOne
      template: {get_file: web.yaml}
      parameters:
        flavor: {get_param: flavor}
        image: {get_param: image}
