heat_template_version: 2013-05-23
description: A load-balancer server
parameters:
  image:
    type: string
    description: Image used for servers
  key_name:
    type: string
    description: SSH key to connect to the servers
  flavor:
    type: string
    description: flavor used by the servers
  pool_id:
    type: string
    description: Pool to contact
  user_data:
    type: string
    description: Server user_data
    default: "abc"
  metadata:
    type: json
  up_net:
    type: string
    description: Network used by the server
  down_net:
    type: string
    description: Network used by the server
  swift_net:
    type: string
    description: Network used by the server
  az:
    type: string
    description: Availability zone of the server
  security_group:
    type: string
    description: Security group of the server
  protocol_port:
    type: string
    description: Protocol port used by the server

resources:
  server:
    type: OS::Nova::Server
    properties:
      user_data_format: RAW
      flavor: {get_param: flavor}
      image: {get_param: image}
      key_name: {get_param: key_name}
      metadata: {get_param: metadata}
      user_data: {get_param: user_data}
      networks: [
        {network: {get_param: swift_net}},
        {network: {get_param: up_net}},
        {network: {get_param: down_net}}
      ]
      security_groups: [ {get_param: security_group} ]
      availability_zone: {get_param: az}
      config_drive: true
  member:
    type: OS::Neutron::PoolMember
    properties:
      pool_id: {get_param: pool_id}
      address: {get_attr: [server, first_address]}
      protocol_port: {get_param: protocol_port}

outputs:
  server_ip:
    description: IP Address of the load-balanced server.
    value: { get_attr: [server, first_address] }
  lb_member:
    description: LB member details.
    value: { get_attr: [member, show] }

