heat_template_version: 2013-05-23
resources:
  server:
    type: OS::Nova::Server
    properties:
      metadata: {"metering.stack": {get_param: "OS::stack_id"}}
      flavor: m1.tiny
  cpu_alarm_high:
    type: OS::Ceilometer::Alarm
    properties:
      description: Scale-up if the average CPU > 50% for 1 minute
      meter_name: cpu_util
      statistic: avg
      period: 60
      evaluation_periods: 1
      threshold: 50
      matching_metadata: {'metadata.user_metadata.stack': {get_param: "OS::stack_id"}}
      comparison_operator: gt
