heat_template_version: 2013-05-23
description: Custom Contraints
parameters:
    network:
        type: string
        default: private
        constraints:
            - custom_constraint: neutron.network
