heat_template_version: 2013-05-23

description: Just a simple test template.

parameters:
  key_name:
    type: string
    description: Name of an existing key pair to use for the instance.
    default: lxiaojun
  flavor:
    type: string
    description: Flavor for the server to be created.
    default: m1.tiny
    constraints:
      - custom_constraint: nova.flavor
  image:
    type: string
    description: The image to use for the server.
    default: cirros-0.3.1-x86_64-uec

resources:
  my_server:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image }
      flavor: { get_param: flavor }

outputs:
  server_ip:
    description: The IP address of the deployed server.
    value: { get_attr: [my_server, networks, private, 0] }
