heat_template_version: 2013-05-23
parameters:
  image:
    type: string
    default: cirros-0.3.2-x86_64-uec
  flavor:
    type: string
    default: m1.tiny
resources:
  server:
    type: OS::Nova::Server
    properties:
      image: {get_param: image}
      flavor: {get_param: flavor}
  vol:
    type: OS::Cinder::Volume
    properties:
      size: 1
  att:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: {get_resource: server}
      volume_id: {get_resource: vol}
