heat_template_version: 2013-05-23
parameters:
  flavor:
    type: string
    default: m1.small
  image:
    type: string
    default: fedora-sc
  key:
    type: string
    default: lxiaojun
resources:
  stack:
    type: OS::Heat::Stack
    properties:
      context:
        region_name: RegionOne
      template: {get_file: web.yaml}
      parameters:
        flavor: {get_param: flavor}
        image: {get_param: image}
        key: {get_param: key}
