heat_template_version: 2013-05-23
parameters:
  flavor:
    type: string
    default: m1.nano

resources:
  port:
    type: OS::Neutron::Port
    properties:
      network: private

  server:
    type: OS::Nova::Server
    properties:
      image: cirros-0.3.2-x86_64-uec
      flavor: {get_param: flavor}
      networks:
        - port: {get_resource: port}

outputs:
  port_id:
    value: {get_resource: port}
