heat_template_version: 2013-05-23
parameters:
  flavor:
    type: string
    default: m1.nano
  image:
    type: string
    default: cirros-0.3.2-x86_64-uec

resources:
  port:
    type: OS::Neutron::Port
    properties:
      network: private

  server:
    type: OS::Nova::Server
    properties:
      image: {get_param: image}
      flavor: {get_param: flavor}
      networks:
        - port: d493ae33-369b-43ce-b65b-1b471deb2f94

outputs:
  port_id:
    value: {get_resource: port}
