heat_template_version: 2016-04-08
parameters:
  flavor:
    type: string
    default: demo
  image:
    type: string
    default: fedora-sc
  ssh_key:
    type: string
    default: demo
  network:
    type: string
    default: private

resources:
  server:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: flavor}
      image: {get_param: image}
      key_name: {get_param: ssh_key}
      networks:
        - network: {get_param: network}
      user_data_format: RAW
      user_data: |
        #!/bin/sh
        echo '### hello world ###' |tee /tmp/helloworld

outputs:
  ip:
    description: Address of this server
    value: {get_attr: [server, networks, {get_param: network}, 0]}
