heat_template_version: 2013-05-23
resources:
  port:
    type: OS::Neutron::Port
    properties:
      network: private
  fip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: public
      port_id: {get_resource: port}
