heat_template_version: 2013-05-23
parameters:
  image:
    type: string
    default: cirros-0.3.2-x86_64-uec
  flavor:
    type: string
    default: m1.nano
resources:
  stack_region_1:
    type: OS::Heat::Stack
    properties:
      context:
        region_name: RegionOne
      template: {get_file: one_server.yaml}
      parameters:
        flavor: {get_param: flavor}
        image: {get_param: image}

  stack_region_2:
    type: OS::Heat::Stack
    properties:
      context:
        region_name: RegionTwo
      template: {get_file: one_server.yaml}
      parameters:
        flavor: {get_param: flavor}
        image: {get_param: image}

